const Engineer = [
    {
      imageUrl: "https://images.pexels.com/photos/4307869/pexels-photo-4307869.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "John Doe",
      age: 28,
      fav: "React",
      lang: "JavaScript",
      role: "Frontend Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/6626882/pexels-photo-6626882.jpeg?auto=compress&cs=tinysrgb&h=204&fit=crop&w=228&dpr=1",
      name: "Jane Smith",
      age: 32,
      fav: "Node.js",
      lang: "JavaScript",
      role: "Backend Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/5490276/pexels-photo-5490276.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Michael Johnson",
      age: 25,
      fav: "Vue.js",
      lang: "JavaScript",
      role: "Full Stack Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/5792641/pexels-photo-5792641.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Emily Brown",
      age: 29,
      fav: "Angular",
      lang: "TypeScript",
      role: "Frontend Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/5384445/pexels-photo-5384445.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Robert Lee",
      age: 30,
      fav: "Python",
      lang: "Python",
      role: "Data Scientist",
    },
    {
      imageUrl: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Sophia Wilson",
      age: 26,
      fav: "Django",
      lang: "Python",
      role: "Backend Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "William Johnson",
      age: 31,
      fav: "React Native",
      lang: "JavaScript",
      role: "Mobile App Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Olivia Smith",
      age: 27,
      fav: "Swift",
      lang: "Swift",
      role: "iOS Developer",
    },
    {
      imageUrl: "https://media.istockphoto.com/id/1309328823/photo/headshot-portrait-of-smiling-male-employee-in-office.jpg?b=1&s=612x612&w=0&k=20&c=eU56mZTN4ZXYDJ2SR2DFcQahxEnIl3CiqpP3SOQVbbI=",
      name: "Ethan Wilson",
      age: 28,
      fav: "Java",
      lang: "Java",
      role: "Android Developer",
    },
    {
      imageUrl: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Ava Brown",
      age: 29,
      fav: "C#",
      lang: "C#",
      role: "Game Developer",
    },
  ];
  
  export default Engineer